name: push deb
env:
  apt-version: "1.27"
on:
  workflow_dispatch:
      inputs:
        tag:
          description: 'Create slurm debian packages for release tag'
          required: true
          type: string
jobs:
  script:
    runs-on: ubuntu-22.04
    name: Create Debian packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
           ref: ${{ github.event.inputs.tag }}
      - name: Login to docker hub
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
        run: sudo docker login -u $DOCKER_USER -p $DOCKER_PWD
      - name: pre-cleanup the docker
        run: sudo docker system prune -a -f
      - name: Create debian package
        shell: bash
        run: |
            sudo apt-get update
            sudo apt-get install build-essential fakeroot devscripts libmysqlclient-dev equivs -y
            sudo mk-build-deps -i --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control
            sudo debuild -b -uc -us
            sudo mkdir /tmp/slurm-deb-pkgs
            sudo cp ../*.deb /tmp/slurm-deb-pkgs
      - name: Pushing Debian packages
        shell: bash
        env: 
           docker_pass: f5e2c72a-ac20-4fc9-9cc1-cab0406af582
        run: |
            cd $HOME
            mkdir local-bin/
            curl -L https://carvel.dev/install.sh | K14SIO_INSTALL_BIN_DIR=local-bin bash
            export PATH=$PWD/local-bin/:$PATH
            sudo cp local-bin/* /usr/bin/
            #sudo docker login -u kubedrona -p ${{ env.docker_pass }}
            cd /tmp/slurm-deb-pkgs
            echo Pushing bundle "$*"
            echo $@
            sudo imgpkg push -f . -i docker.io/coredgeio/slurm-debian-ubuntu_22.04_x86-64:v${{ github.event.inputs.tag }}
            echo Done
      - name: cleanup the docker
        run: sudo docker logout && sudo docker system prune -a -f
