name: push deb
env:
  VERSION: "23.11.3"
  apt-version: "1.27"
on: [ workflow_dispatch ]
jobs:
  script:
    runs-on: ubuntu-22.04
    name: Create Debian packages
    steps: 
      - name: Create debian package
        shell: bash
        run: |
            sudo apt-get install build-essential fakeroot devscripts libmysqlclient-dev equivs -y
            sudo mk-build-deps -i --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control
            sudo debuild -b -uc -us
            sudo mkdir /tmp/slurm-deb-pkgs
            sudo cp ../*.deb /tmp/slurm-deb-pkgs
      - name: Pushing Debian packages
        shell: bash
        env: 
           docker_pass: b0d2dd30-cca5-48ee-aa01-45a94fdc8751
        run: |
            cd $HOME
            mkdir local-bin/
            curl -L https://carvel.dev/install.sh | K14SIO_INSTALL_BIN_DIR=local-bin bash
            export PATH=$PWD/local-bin/:$PATH
            sudo cp local-bin/* /usr/bin/
            docker login -u kubedrona -p ${{ env.docker_pass }}
            cd /tmp/slurm-deb-pkgs
            echo Pushing bundle "$*"
            echo $@
            imgpkg push -f . -i docker.io/coredgeio/slurm-debian-ubuntu_22.04_x86-64:v${{env.VERSION}}
            echo Done
